const esModules = [
  "bail",
  "comma-separated-tokens",
  "decamelize",
  "decode-named-character-reference",
  "fetch-blob",
  "hast-util-whitespace",
  "humanize-string",
  "is-plain-obj",
  "lodash-es",
  "mdast-util-*",
  "micromark",
  "pretty-bytes",
  "property-information",
  "react-markdown",
  "remark-*",
  "space-separated-tokens",
  "trim-lines",
  "trough",
  "unified",
  "unist-*",
  "uuid",
  "vfile",
].join("|");
export default {
  transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/jest-setup.ts", "jest-canvas-mock"],
  moduleDirectories: ["node_modules", "src"],
};
